### ISSUE TITLE
cudnn error

### ISSUE THREAD

**Issue by zcyang** [facebook/fb.resnet.torch#35]
I installed cudnn 4 and installed the cudnn torch bindings.

When I ran 
```th main.lua -dataset cifar10 -nGPU 1 -depth 20```
I got the following error
```
=> Creating model from file: models/resnet.lua
 | ResNet-20 CIFAR-10
=> Training epoch # 1
/home/zichaoy/hdd/zichaoy/torch/install/bin/luajit: ...hdd/zichaoy/torch/install/share/lua/5.1/nn/Container.lua:67:
In 1 module of nn.Sequential:
...y/hdd/zichaoy/torch/install/share/lua/5.1/cudnn/init.lua:58: Error in CuDNN: CUDNN_STATUS_NOT_SUPPORTED (cudnnSetFilterNdDescriptor)
stack traceback:
	[C]: in function 'error'
	...y/hdd/zichaoy/torch/install/share/lua/5.1/cudnn/init.lua:58: in function 'errcheck'
	...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:45: in function 'resetWeightDescriptors'
	...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:358: in function <...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:357>
	[C]: in function 'xpcall'
	...hdd/zichaoy/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	...dd/zichaoy/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	./train.lua:56: in function 'train'
	main.lua:49: in main chunk
	[C]: in function 'dofile'
	...haoy/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

WARNING: If you see a stack trace below, it doesn't point to the place where this error occured. Please use only the one above.
stack traceback:
	[C]: in function 'error'
	...hdd/zichaoy/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
	...dd/zichaoy/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	./train.lua:56: in function 'train'
	main.lua:49: in main chunk
	[C]: in function 'dofile'
	...haoy/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

```

Any suggestions on how to fix this? Many thanks!

**Comment by soumith** [comment]
is your cuda version too old? less than 7.0? Or maybe your CUDA driver is too old?

**Comment by zcyang** [comment]
It's unlikely, I installed the lasted cuda 7.5 with driver ```NVIDIA-SMI 352.39     Driver Version: 352.39```

**Comment by zcyang** [comment]
fixed by reinstalling torch
