### ISSUE TITLE
Indicate GPU_id when training in Multi-gpu mode

### ISSUE THREAD

**Issue by hli2020** [facebook/fb.resnet.torch#39]
Hi, say there are 16 cards in one machine, and I want to use 4 cards specifically, gpu_id=9,10,11,12. (1-indexed) How to target them? tried several solutions, all failed.
- add `CUDDA_VISIBLE_DEVICES=9,10,11,12  th xxx.lua`, failed.
- add a new flag `opt.GPUStartId` in opts.lua and change [Line 90](https://github.com/facebook/fb.resnet.torch/blob/master/models%2Finit.lua#L90) in `models/init.lua` to ` local gpus = torch.range(opt.GPUStartId, opt.nGPU+opt.GPUStartId-1):totable()`, and the following error occurs:

=> Training epoch # 1	
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-5821/cutorch/lib/THC/generic/THCStorage.cu line=48 error=77 : an illegal memory access was encountered

I am guessing I need to write some `cutorch:setDevice()` around [Line 94](https://github.com/facebook/fb.resnet.torch/blob/master/models%2Finit.lua#L94)????

Thanks so much!

**Comment by colesbury** [comment]
The first option is the right way to do it. There's a typo in the issue (`CUDDA` vs `CUDA`); not sure if you had a typo when you ran it. How did it fail?

**Comment by hli2020** [comment]
Problem solved! I made the typo `CUDDA`. so silly. thanks! now turn to try imagenet! finger crossed.

**Comment by ajeetksingh** [comment]
Hi,
I did the exact step as mentioned in the first step of @hli2020 sans the typo, but somehow, it's still assigning the process to other GPUs. Below is the command which I am running:

`CUDA_VISIBLE_DEVICES=2,3 th main.lua -dataset cifar10 -nGPU 2 -batchSize 128 -depth 20 -netType resnet -LR 0.005 -nEpochs 150`

Assuming I have to run it on the GPUs 2 and 3. GPUs are 0-indexed.

Thanks :)

**Comment by ajeetksingh** [comment]
The command prints `2`.

Anyways, I resolved the issue. Apparently, the  problem was with mapping of numbers to GPU ids.
e.g. `CUDA_VISIBLE_DEVICES=2,3` would correspond to 0th and 1st GPU not the 2nd and 3rd.

So I just changed the command to `CUDA_VISIBLE_DEVICES=0,1` and it started running on the 2nd and 3rd. I still don't know, why does it happen? :(
